/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    'get-started',
    {
      type: 'category',
      label: 'Basic Concepts',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: ['basic-concepts/items-types', 'basic-concepts/contract','basic-concepts/max'],
    },
    {
      type: 'category',
      label: 'API',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    'faq',
  ],
  examples: [
    {
      type: 'autogenerated',
      dirName: 'examples',
    },
  ],
};

module.exports = sidebars;
